---

- block:
    - when: apisix_dashboard_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: apisix_dashboard_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-apisix-dashboard
    - install-all
    - install-apisix-dashboard

- block:
    - when: not apisix_dashboard_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-apisix-dashboard
