# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of APISIX Dashboard systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ apisix_dashboard_identifier }}.service"
  register: apisix_dashboard_service_stat

- name: Uninstall APISIX Dashboard systemd services and files
  when: apisix_dashboard_service_stat.stat.exists | bool
  block:
    - name: Ensure APISIX Dashboard systemd service is stopped
      ansible.builtin.service:
        name: "{{ apisix_dashboard_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure APISIX Dashboard systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ apisix_dashboard_identifier }}.service"
        state: absent

    - name: Ensure APISIX Dashboard path does not exist
      ansible.builtin.file:
        path: "{{ apisix_dashboard_base_path }}"
        state: absent
