---

- name: Fail if required APISIX Dashboard settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when | bool and vars[item.name] == ''"
  with_items:
    - {'name': 'apisix_dashboard_identifier', 'when': true}
    - {'name': 'apisix_dashboard_uid', 'when': true}
    - {'name': 'apisix_dashboard_gid', 'when': true}
    - {'name': 'apisix_dashboard_hostname', 'when': true}
    - {'name': 'apisix_dashboard_path_prefix', 'when': true}
    - {'name': 'apisix_dashboard_container_network', 'when': true}
    - {'name': 'apisix_dashboard_config_authentication_secret', 'when': true}

# We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
# Knowing that `apisix_dashboard_path_prefix` does not end with a slash
# ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
- name: Fail if apisix_dashboard_path_prefix ends with a slash
  ansible.builtin.fail:
    msg: >-
      apisix_dashboard_path_prefix (`{{ apisix_dashboard_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/apisix`).
  when: "apisix_dashboard_path_prefix != '/' and apisix_dashboard_path_prefix[-1] == '/'"
