# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 - 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - {'old': 'apisix_dashboard_systemd_required_systemd_services_list_default', 'new': 'apisix_dashboard_systemd_required_services_list_default'}
    - {'old': 'apisix_dashboard_systemd_required_systemd_services_list_auto', 'new': 'apisix_dashboard_systemd_required_services_list_auto'}
    - {'old': 'apisix_dashboard_systemd_required_systemd_services_list_custom', 'new': 'apisix_dashboard_systemd_required_services_list_custom'}

- name: Fail if required APISIX Dashboard settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when | bool and vars[item.name] == ''"
  with_items:
    - {'name': 'apisix_dashboard_identifier', 'when': true}
    - {'name': 'apisix_dashboard_uid', 'when': true}
    - {'name': 'apisix_dashboard_gid', 'when': true}
    - {'name': 'apisix_dashboard_hostname', 'when': true}
    - {'name': 'apisix_dashboard_path_prefix', 'when': true}
    - {'name': 'apisix_dashboard_container_network', 'when': true}
    - {'name': 'apisix_dashboard_config_authentication_secret', 'when': true}

# We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
# Knowing that `apisix_dashboard_path_prefix` does not end with a slash
# ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
- name: Fail if apisix_dashboard_path_prefix ends with a slash
  ansible.builtin.fail:
    msg: >-
      apisix_dashboard_path_prefix (`{{ apisix_dashboard_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/apisix`).
  when: "apisix_dashboard_path_prefix != '/' and apisix_dashboard_path_prefix[-1] == '/'"
